baseURL               = "https://yunfangame.github.io"
languageCode          = "zh-CN"
title                 = "AI & 工具导航站 |共享账号&苹果ID|在线工具百宝箱 | 万象宝盒-上网导航,出海网站导航,免费资源大全"
keywords              = "AI & 工具导航站 |共享账号&苹果ID|在线工具百宝箱 | 万象宝盒"
description       = "一个集搜索、AI工具和常用网站于一体的综合导航平台。在这里，您可以一站式访问热门的社交媒体、视频平台、常用工具，共享账号并轻松体验免费的在线AI问答服务。旨在帮助您节省时间，提高工作与生活效率。"
theme                 = "NavPage-Hugo-Theme"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    author            = "wanxiangbaohe"
    description       = "一个集搜索、AI工具和常用网站于一体的综合导航平台。在这里，您可以一站式访问热门的社交媒体、视频平台、常用工具，共享账号并轻松体验免费的在线AI问答服务。旨在帮助您节省时间，提高工作与生活效率。"
    upload            = "./upload/"
    about             = "./about/"	                               		# 左侧导航栏的"关于我们"页面(./about)
    enablePreLoad     = true                                           		# 网站完全打开前预加载动画
    textPreLoad       = "万象宝盒--适合中国人的导航"                           		# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar     = false                                          		# 默认展开左侧边导航栏
    nightMode         = false							# 默认站点为深色(夜间)模式
    yiyan             = true                                        		# 默认启用一言服务
    fancybox          = true                                                	# 使用 Fancybox 实现图片灯箱/放大功能

[params.logo] 
    logosType         = "PATH"                                   		# 站点logo获取方式(API/PATH)
    logosAPI          = "https://favicon.im/" 					# 通过 API 的方式获取图标, logosType=API 生效
    largerSize        = true                                    		# larger=true, logosType=API 生效
    logosPath         = "logos/"				# 网站每个导航地址logo存放地址, logosType=PATH 时生效
    defaultLogo       = "logos/default.webp"      				# logo图片资源不存在或错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功

[params.images]
    favicon           = "imgs/px.png"
    searchImageL      = "imgs/bg-dna.jpg"					# 搜索部分浅色背景图
    searchImageD      = "imgs/bg-dna.jpg"					# 搜索部分深色背景图
    logoExpandLight   = "imgs/px-expand-dark.png"
    logoExpandDark    = "imgs/px-expand-light.png"
    logoCollapseLight = "images/px-collapse.png"
    logoCollapseDark  = "images/px-collapse.png"

[params.tpweather]
    key = "085791e805a24491b43b06cf58ab31e7"					# 心知天气(https://www.seniverse.com/widgetv3)

[params.seo]
    baiduhmid       = ''                                                        # 百度统计 hm.src 的 ID
    baiduSiteVer    = ''                                                        # 百度HTML标签验证(baidu-site-verification)
    tj51laid        = '3JHwtbgyvMReDNFU'                                        # 51.LA 网站统计
    tj51lack        = '3JHwtbgyvMReDNFU'
    GoogleAdsClient = ''

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; 2021 - {year} By [万象宝盒]() | [Bio IT 爱好者]() | [粤ICP备16023717号](http://beian.miit.gov.cn/) | [Netlify](https://app.netlify.com/) <br/>本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：<a href="mailto:yunfangame@gmail.com?subject=万象宝盒网址导航意见反馈" target="_blank">yunfangame@gmail.com</a> <br/><script id="LA-DATA-WIDGET" crossorigin="anonymous" charset="UTF-8" src="https://v6-widget.51.la/v6/3JHwtbgyvMReDNFU/quote.js?theme=#1690FF,#282A2D,#282A2D,#E87371,#FFFFFF,#1690FF,12&f=12&display=1,0,1,1,1,1,1,1"></script>'
